'use client';

import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Boxes, BriefcaseBusiness, ChevronDown, CircleDollarSign, ClipboardCheck, FileText, Grid2X2, Laptop, LayoutDashboard, Menu, PackageCheck, Plus, Search, Settings, ShieldCheck, ShoppingCart, Truck, Users, X, Zap } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const chartData = [{day:'01 Aug',sales:18,stock:72},{day:'05 Aug',sales:24,stock:68},{day:'09 Aug',sales:20,stock:75},{day:'13 Aug',sales:34,stock:62},{day:'17 Aug',sales:29,stock:58}];
const activity = [
  ['Sale SAL-2026-000184','Apex Retail · 4 POS terminals','Confirmed','today'],
  ['Goods received BAT-2026-000073','TechCore Distributors · 18 laptops','Received','today'],
  ['Warranty claim WAR-2026-000021','Mavuno Foods · POS-884021','Needs review','1h ago'],
  ['Transfer TRF-2026-000041','Harare Central → Bulawayo Branch','In transit','3h ago'],
];
const nav = [
  { label:'Overview', icon:LayoutDashboard }, { label:'Sales & CRM', icon:BriefcaseBusiness, count:'12' }, { label:'Inventory', icon:Boxes }, { label:'Procurement', icon:ShoppingCart }, { label:'Job cards', icon:ClipboardCheck, count:'8' }, { label:'Warranty', icon:ShieldCheck }, { label:'Reports', icon:FileText },
];

function StatCard({ label, value, change, note, icon:Icon, tone='blue' }: {label:string;value:string;change:string;note:string;icon:React.ElementType;tone?:string}) {
  return <div className="stat-card"><div className="stat-top"><span className={`icon-box ${tone}`}><Icon size={17}/></span><span className={change.startsWith('-') ? 'change down' : 'change'}>{change.startsWith('-') ? <ArrowDownRight size={13}/> : <ArrowUpRight size={13}/>} {change.replace('-','')}</span></div><div className="stat-value">{value}</div><div className="stat-label">{label}</div><div className="stat-note">{note}</div></div>
}

export default function Home() {
  const [active, setActive] = useState('Overview'); const [dark, setDark] = useState(false); const [menu, setMenu] = useState(false); const [query, setQuery] = useState(''); const [toast, setToast] = useState('');
  const filtered = useMemo(() => activity.filter(a => a.join(' ').toLowerCase().includes(query.toLowerCase())), [query]);
  const notify = (message:string) => { setToast(message); setTimeout(() => setToast(''), 2800); };
  const goToModule = (label:string) => { if (label !== 'Overview') { window.location.href = `/operations?module=${encodeURIComponent(label)}`; return; } setActive(label); };
  return <div className={dark ? 'shell dark' : 'shell'}>
    <aside className={menu ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark"><Zap size={17} fill="currentColor"/></div><div><strong>iPayTech</strong><span>OPS CONSOLE</span></div><button className="mobile-close" onClick={()=>setMenu(false)}><X size={19}/></button></div>
      <div className="workspace-label">WORKSPACE</div><div className="workspace"><div className="workspace-dot">HZ</div><div><strong>Harare HQ</strong><span>All operations</span></div><ChevronDown size={15}/></div>
      <nav>{nav.map(({label,icon:Icon,count}) => <button key={label} className={active===label?'nav-item active':'nav-item'} onClick={()=>{goToModule(label);setMenu(false);}}><Icon size={17}/><span>{label}</span>{count && <b>{count}</b>}</button>)}</nav>
      <div className="sidebar-spacer"/><div className="sidebar-section"><button className="nav-item"><Users size={17}/><span>People & HR</span></button><button className="nav-item"><Settings size={17}/><span>Configuration</span></button></div>
      <div className="user-card"><div className="avatar">AM</div><div><strong>Amara Moyo</strong><span>Chief Operating Officer</span></div><MoreDots/></div>
    </aside>
    <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMenu(true)}><Menu size={21}/></button><div className="crumb"><span>Operations</span><span>/</span><strong>{active}</strong></div><div className="top-actions"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything..."/><kbd>⌘ K</kbd></div><button className="icon-btn" aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark ? <Zap size={18}/> : <Grid2X2 size={18}/>}</button><button className="icon-btn notification" onClick={()=>notify('You have 8 approvals waiting')}><Bell size={18}/><i/></button><div className="top-avatar">AM</div></div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> Live operations</div><h1>Good morning, Amara</h1><p>Here’s what’s happening across iPayTech today.</p></div><div className="heading-actions"><button className="btn secondary" onClick={()=>notify('Report export queued')}><FileText size={16}/> Export report</button><button className="btn primary" onClick={()=>notify('New sale workflow opened')}><Plus size={17}/> New transaction</button></div></div>
        <div className="stats-grid"><StatCard label="Revenue this month" value="$184,290" change="12.8%" note="vs. $163,450 last month" icon={CircleDollarSign}/><StatCard label="Gross profit" value="$61,430" change="8.4%" note="Margin 33.3%" icon={Activity} tone="green"/><StatCard label="Units in stock" value="1,248" change="-4.2%" note="38 below reorder level" icon={Boxes} tone="amber"/><StatCard label="Open job cards" value="42" change="6.1%" note="8 due this week" icon={ClipboardCheck} tone="purple"/></div>
        <div className="grid-main"><section className="panel performance"><div className="panel-header"><div><h2>Performance overview</h2><p>Revenue and stock movement over the last 30 days</p></div><button className="select">Last 30 days <ChevronDown size={14}/></button></div><div className="legend"><span><i className="legend-blue"/>Revenue</span><span><i className="legend-slate"/>Stock movement</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="blue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2f7cf6" stopOpacity={.22}/><stop offset="100%" stopColor="#2f7cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf5"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#8a97aa'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#8a97aa'}}/><Tooltip/><Area type="monotone" dataKey="sales" stroke="#2f7cf6" strokeWidth={2.5} fill="url(#blue)"/><Area type="monotone" dataKey="stock" stroke="#9aa8bd" strokeWidth={1.5} fill="transparent"/></AreaChart></ResponsiveContainer></div></section><section className="panel approvals"><div className="panel-header"><div><h2>Approval inbox</h2><p>Items requiring your attention</p></div><button className="text-btn" onClick={()=>notify('Approval inbox opened')}>View all <ArrowUpRight size={14}/></button></div><div className="approval-total"><strong>08</strong><span>pending approvals</span><div className="approval-bars"><i/><i/><i/><i/><i/><i/></div></div><div className="approval-list"><Approval icon={ShoppingCart} label="Purchase orders" count="03" tone="blue"/><Approval icon={CircleDollarSign} label="Expenses" count="02" tone="amber"/><Approval icon={ShieldCheck} label="Warranty exceptions" count="01" tone="red"/><Approval icon={PackageCheck} label="Stock adjustments" count="02" tone="green"/></div></section></div>
        <div className="grid-bottom"><section className="panel table-panel"><div className="panel-header"><div><h2>Recent activity</h2><p>Latest events from across the operation</p></div><button className="text-btn" onClick={()=>notify('Activity log opened')}>Activity log <ArrowUpRight size={14}/></button></div><div className="activity-table"><div className="table-head"><span>EVENT</span><span>DETAIL</span><span>STATUS</span><span>WHEN</span></div>{filtered.length ? filtered.map((a,i)=><div className="table-row" key={i}><span className="event-cell"><span className={`event-icon e${i}`}><Activity size={14}/></span><strong>{a[0]}</strong></span><span>{a[1]}</span><span><em className={`pill p${i}`}>{a[2]}</em></span><span className="muted">{a[3]}</span></div>) : <div className="empty">No matching activity found.</div>}</div></section><section className="panel stock-panel"><div className="panel-header"><div><h2>Stock by category</h2><p>Current available inventory</p></div><button className="text-btn" onClick={()=>setActive('Inventory')}>View stock <ArrowUpRight size={14}/></button></div><div className="stock-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'POS',value:680},{name:'Laptops',value:418},{name:'Parts',value:150}]} layout="vertical" margin={{left:0,right:20}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#68768c'}} width={58}/><Tooltip cursor={{fill:'transparent'}}/><Bar dataKey="value" fill="#2f7cf6" radius={[0,4,4,0]} barSize={14}/></BarChart></ResponsiveContainer></div><div className="stock-foot"><span><i className="dot blue"/> Available <strong>1,248</strong></span><span><i className="dot amber"/> Reserved <strong>86</strong></span></div></section></div>
      </div></main>{toast && <div className="toast"><span className="toast-check">✓</span>{toast}</div>}
  </div>
}
function Approval({icon:Icon,label,count,tone}:{icon:React.ElementType;label:string;count:string;tone:string}) { return <button className="approval-row"><span className={`approval-icon ${tone}`}><Icon size={15}/></span><span>{label}</span><b>{count}</b><ArrowUpRight size={14}/></button> }
function MoreDots(){ return <span className="more-dots">•••</span> }
