'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, RefreshCw, ScrollText } from 'lucide-react';

type AuditLog = { id: string; action: string; entity_type?: string; entity_id?: string; metadata?: Record<string, unknown>; ip_address?: string; user_agent?: string; created_at: string; actor_name?: string; actor_email?: string };

export default function AuditLogsWorkspace({ query }: { query: string }) {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [selected, setSelected] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [action, setAction] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: '200' }); if (query) params.set('search', query); if (action) params.set('action', action); const response = await fetch(`/api/audit-logs?${params.toString()}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load audit logs.'); setLogs(data.auditLogs || []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load audit logs.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [query, action]);
  const actions = useMemo(() => Array.from(new Set(logs.map(log => log.action))).sort(), [logs]);
  return <section className="ops-panel audit-workspace"><div className="ops-panel-head"><div><h2><ScrollText size={16}/> Organization audit trail</h2><p>CEO-only oversight with searchable actors, entities, metadata, and access context.</p></div><button className="link-btn" onClick={() => void load()}><RefreshCw size={14}/> Refresh</button></div><div className="audit-filters ops-audit-filters"><label><span>Action</span><select value={action} onChange={event => setAction(event.target.value)}><option value="">All actions</option>{actions.map(item => <option key={item}>{item}</option>)}</select></label></div>{error && <p className="workflow-error" role="alert">{error}</p>}{loading ? <div className="empty-state">Loading audit records…</div> : <div className="audit-list">{logs.map(log => <div className={selected === log.id ? 'audit-record selected' : 'audit-record'} key={log.id}><button className="audit-record-main" onClick={() => setSelected(selected === log.id ? null : log.id)}><span className="audit-action"><ScrollText size={14}/><strong>{log.action}</strong></span><span>{log.actor_name || 'System'}<small>{log.actor_email || 'System event'}</small></span><span>{log.entity_type || 'system'}<small>{log.entity_id || 'No entity ID'}</small></span><span>{new Date(log.created_at).toLocaleString('en-GB')}</span><ArrowDownRight size={14}/></button>{selected === log.id && <div className="audit-detail"><div><strong>IP address</strong><span>{log.ip_address || 'Not recorded'}</span></div><div><strong>User agent</strong><span>{log.user_agent || 'Not recorded'}</span></div><div><strong>Metadata</strong><pre>{JSON.stringify(log.metadata || {}, null, 2)}</pre></div></div>}</div>)}{!logs.length && <div className="empty-state">No audit records match this search.</div>}</div>}</section>;
}
