'use client';

import { FormEvent, useEffect, useState } from 'react';
import { BriefcaseBusiness, Check, FileText, Plus, RotateCcw, Users, X } from 'lucide-react';

type Client = { id: string; code: string; name: string; contact_name?: string; phone?: string; status: string };
type Opportunity = { id: string; name: string; stage: string; value: string; client_name?: string };
type QuoteItem = { id: string; sku: string; description: string; quantity: number; unitPrice: string };
type Quote = { id: string; number: string; status: string; total: string; client_name: string; items: QuoteItem[] };
type SaleItem = { id: string; serialNumber: string; sku: string; description: string; returned: boolean };
type Sale = { id: string; number: string; status: string; total: string; client_name: string; items: SaleItem[] };
type Inventory = { id: string; serial_number: string; sku: string; description: string; status: string };
type Lead = { id: string; name: string; source?: string; status: string; client_name?: string; owner_name?: string };

export default function CrmWorkspace({ notify }: { notify: (message: string) => void }) {
  const [clients, setClients] = useState<Client[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [quotes, setQuotes] = useState<Quote[]>([]); const [sales, setSales] = useState<Sale[]>([]);
  const [dialog, setDialog] = useState<'client' | 'lead' | 'opportunity' | 'quotation' | 'convert' | 'return' | null>(null); const [selectedQuote, setSelectedQuote] = useState<Quote | null>(null); const [selectedSale, setSelectedSale] = useState<Sale | null>(null); const [error, setError] = useState('');
  const load = async () => { setError(''); try { const responses = await Promise.all(['/api/crm/clients', '/api/crm/leads', '/api/crm/opportunities', '/api/crm/quotations', '/api/crm/sales'].map(url => fetch(url, { cache: 'no-store' }))); if (responses.some(response => !response.ok)) throw new Error('Live CRM data is unavailable.'); const data = await Promise.all(responses.map(response => response.json())); setClients(data[0].clients || []); setLeads(data[1].leads || []); setOpportunities(data[2].opportunities || []); setQuotes(data[3].quotations || []); setSales(data[4].sales || []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Live CRM data is unavailable.'); } };
  useEffect(() => { void load(); }, []);
  const saved = (message: string) => { setDialog(null); notify(message); void load(); };
  const createDocument = async (saleId: string, kind: 'invoice' | 'delivery-note') => { const response = await fetch(`/api/crm/sales/${saleId}/${kind}`, { method: 'POST' }); const data = await response.json(); if (!response.ok) { notify(data.error || `Unable to generate ${kind}.`); return; } notify(`${kind === 'invoice' ? 'Invoice' : 'Delivery note'} ${data.invoice?.number || data.deliveryNote?.number} generated`); };
  const createCommission = async (saleId: string) => { const response = await fetch(`/api/crm/sales/${saleId}/commission`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rate: 5 }) }); const data = await response.json(); if (!response.ok) { notify(data.error || 'Unable to calculate commission.'); return; } notify(`Provisional commission $${Number(data.commission.amount).toFixed(2)} calculated`); };
  return <>
    <div className="ops-kpis"><LiveKpi label="Live clients" value={clients.length} note="CRM accounts in PostgreSQL" icon={<Users size={16}/>} tone="blue"/><LiveKpi label="Leads" value={leads.length} note="Source and owner tracked" icon={<Users size={16}/>} tone="purple"/><LiveKpi label="Quotations" value={quotes.length} note="Quote-to-sale workflow" icon={<FileText size={16}/>} tone="amber"/><LiveKpi label="Confirmed sales" value={sales.length} note="Serialized conversion records" icon={<Check size={16}/>} tone="green"/></div>
    <div className="workflow-actions crm-actions"><button className="ops-btn ghost" onClick={() => setDialog('client')}><Plus size={15}/> Add client</button><button className="ops-btn ghost" onClick={() => setDialog('lead')}><Plus size={15}/> New lead</button><button className="ops-btn ghost" onClick={() => setDialog('opportunity')} disabled={!clients.length}><Plus size={15}/> New opportunity</button><button className="ops-btn blue" onClick={() => setDialog('quotation')} disabled={!clients.length}><Plus size={15}/> New quotation</button><button className="link-btn" onClick={() => void load()}>Refresh</button></div>
    {error && <p className="workflow-error" role="alert">{error}</p>}
    <div className="ops-grid-two"><Panel title="Live client accounts" subtitle="CRM records available to quotations and jobs"><div className="data-table"><TableHead labels={['Client','Code','Contact','Status']}/>{clients.slice(0, 8).map(client => <div className="data-row" key={client.id}><div><strong>{client.name}</strong><small>{client.contact_name || 'No contact'}</small></div><span>{client.code}</span><span>{client.phone || '—'}</span><Status value={client.status}/></div>)}{!clients.length && <div className="empty-state"><Users size={22}/><strong>No live clients</strong><span>Add a client to start CRM workflows.</span></div>}</div></Panel><Panel title="Lead management" subtitle="Capture source, ownership, and qualification state"><div className="data-table"><TableHead labels={['Lead','Client','Source','Status']}/>{leads.slice(0, 8).map(lead => <div className="data-row" key={lead.id}><strong>{lead.name}</strong><span>{lead.client_name || 'Unassigned'}</span><span>{lead.source || '—'}</span><Status value={lead.status}/></div>)}{!leads.length && <div className="empty-state"><Users size={22}/><strong>No live leads</strong><span>Create a lead to begin qualification.</span></div>}</div></Panel></div>
    <Panel title="Opportunity pipeline" subtitle="Lead and opportunity ownership"><div className="data-table"><TableHead labels={['Opportunity','Client','Stage','Value']}/>{opportunities.slice(0, 8).map(opportunity => <div className="data-row" key={opportunity.id}><strong>{opportunity.name}</strong><span>{opportunity.client_name || 'Unassigned'}</span><Status value={opportunity.stage}/><span>{Number(opportunity.value || 0).toLocaleString(undefined, { style: 'currency', currency: 'USD' })}</span></div>)}{!opportunities.length && <div className="empty-state"><BriefcaseBusiness size={22}/><strong>No opportunities</strong><span>Create one from a live client.</span></div>}</div></Panel>
    <Panel title="Quotations and confirmed sales" subtitle="Convert exact live serials, generate documents, calculate commission, and process returns"><div className="data-table"><TableHead labels={['Record','Client','Total','Status','Actions']}/>{quotes.map(quote => <div className="data-row" key={quote.id}><div><strong>{quote.number}</strong><small>{quote.items.length} line(s)</small></div><span>{quote.client_name}</span><span>${Number(quote.total).toLocaleString()}</span><Status value={quote.status}/><button className="row-action" disabled={quote.status === 'Converted'} onClick={() => { setSelectedQuote(quote); setDialog('convert'); }}><Check size={14}/> Convert</button></div>)}{sales.map(sale => <div className="data-row" key={sale.id}><div><strong>{sale.number}</strong><small>{sale.items.length} serial(s)</small></div><span>{sale.client_name}</span><span>${Number(sale.total).toLocaleString()}</span><Status value={sale.status}/><div className="transfer-card-actions"><button className="row-action" onClick={() => void createDocument(sale.id, 'invoice')}><FileText size={14}/> Invoice</button><button className="row-action" onClick={() => void createDocument(sale.id, 'delivery-note')}><FileText size={14}/> Delivery note</button><button className="row-action" onClick={() => void createCommission(sale.id)}><Check size={14}/> Commission</button><button className="row-action" onClick={() => { setSelectedSale(sale); setDialog('return'); }}><RotateCcw size={14}/> Return</button></div></div>)}{!quotes.length && !sales.length && <div className="empty-state"><FileText size={22}/><strong>No quotations or sales</strong><span>Create a quotation to begin the conversion workflow.</span></div>}</div></Panel>
    {dialog === 'client' && <ClientDialog close={() => setDialog(null)} saved={() => saved('Client created')}/>}
    {dialog === 'lead' && <LeadDialog clients={clients} close={() => setDialog(null)} saved={() => saved('Lead created')}/>}
    {dialog === 'opportunity' && <OpportunityDialog clients={clients} close={() => setDialog(null)} saved={() => saved('Opportunity created')}/>}
    {dialog === 'quotation' && <QuotationDialog clients={clients} close={() => setDialog(null)} saved={() => saved('Quotation created')}/>}
    {dialog === 'convert' && selectedQuote && <ConvertDialog quote={selectedQuote} close={() => setDialog(null)} saved={() => saved('Sale confirmed and warranty coverage created')}/>}
    {dialog === 'return' && selectedSale && <ReturnDialog sale={selectedSale} close={() => setDialog(null)} saved={() => saved('Return completed')}/>}
  </>;
}

function Dialog({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div className="workflow-dialog-backdrop"><div className="workflow-dialog" role="dialog" aria-modal="true"><div className="workflow-dialog-head"><h3>{title}</h3><button onClick={close} aria-label="Close"><X size={16}/></button></div>{children}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="workflow-field"><span>{label}</span>{children}</label>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="ops-panel"><div className="ops-panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section>; }
function TableHead({ labels }: { labels: string[] }) { return <div className="table-head ops-table-head">{labels.map(label => <span key={label}>{label}</span>)}</div>; }
function Status({ value }: { value: string }) { const key = value.toLowerCase().replaceAll(' ', '-'); return <span className={`status ${key}`}>{value}</span>; }
function LiveKpi({ label, value, note, icon, tone }: { label: string; value: number; note: string; icon: React.ReactNode; tone: string }) { return <div className="ops-kpi"><span className={`kpi-icon ${tone}`}>{icon}</span><strong>{value}</strong><span>{label}</span><small>{note}</small></div>; }

function ClientDialog({ close, saved }: { close: () => void; saved: () => void }) { const [form, setForm] = useState({ name: '', contactName: '', phone: '', email: '', clientType: 'Organisation' }); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch('/api/crm/clients', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to create client.'); return; } saved(); }; return <Dialog title="Add client" close={close}><form className="workflow-form" onSubmit={submit}><Field label="Name"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field label="Contact name"><input value={form.contactName} onChange={e => setForm({ ...form, contactName: e.target.value })}/></Field><div className="workflow-form-grid"><Field label="Phone"><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></Field></div>{error && <p className="workflow-error">{error}</p>}<Actions close={close}/></form></Dialog>; }
function LeadDialog({ clients, close, saved }: { clients: Client[]; close: () => void; saved: () => void }) { const [form, setForm] = useState({ name: '', clientId: '', source: 'Website', notes: '' }); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch('/api/crm/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, clientId: form.clientId || undefined }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to create lead.'); return; } saved(); }; return <Dialog title="New lead" close={close}><form className="workflow-form" onSubmit={submit}><Field label="Lead name"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field label="Existing client (optional)"><select value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })}><option value="">Unassigned</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><Field label="Source"><input value={form.source} onChange={e => setForm({ ...form, source: e.target.value })}/></Field><Field label="Notes"><textarea rows={3} value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></Field>{error && <p className="workflow-error">{error}</p>}<Actions close={close} label="Create lead"/></form></Dialog>; }
function OpportunityDialog({ clients, close, saved }: { clients: Client[]; close: () => void; saved: () => void }) { const [form, setForm] = useState({ name: '', clientId: clients[0]?.id || '', value: '0' }); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch('/api/crm/opportunities', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, value: Number(form.value) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to create opportunity.'); return; } saved(); }; return <Dialog title="New opportunity" close={close}><form className="workflow-form" onSubmit={submit}><Field label="Opportunity name"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field label="Client"><select value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })}>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><Field label="Value"><input type="number" min="0" step="0.01" value={form.value} onChange={e => setForm({ ...form, value: e.target.value })}/></Field>{error && <p className="workflow-error">{error}</p>}<Actions close={close}/></form></Dialog>; }
function QuotationDialog({ clients, close, saved }: { clients: Client[]; close: () => void; saved: () => void }) { const [form, setForm] = useState({ clientId: clients[0]?.id || '', sku: '', description: '', quantity: '1', unitPrice: '0' }); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch('/api/crm/quotations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clientId: form.clientId, items: [{ sku: form.sku, description: form.description, quantity: Number(form.quantity), unitPrice: Number(form.unitPrice) }] }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to create quotation.'); return; } saved(); }; return <Dialog title="New quotation" close={close}><form className="workflow-form" onSubmit={submit}><Field label="Client"><select value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })}>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><div className="workflow-form-grid"><Field label="SKU"><input required value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })}/></Field><Field label="Quantity"><input required type="number" min="1" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })}/></Field></div><Field label="Description"><input required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></Field><Field label="Unit price"><input required type="number" min="0" step="0.01" value={form.unitPrice} onChange={e => setForm({ ...form, unitPrice: e.target.value })}/></Field>{error && <p className="workflow-error">{error}</p>}<Actions close={close}/></form></Dialog>; }

function ConvertDialog({ quote, close, saved }: { quote: Quote; close: () => void; saved: () => void }) { const [inventory, setInventory] = useState<Inventory[]>([]); const [selected, setSelected] = useState<Record<string, string[]>>({}); const [error, setError] = useState(''); useEffect(() => { void fetch('/api/inventory?status=Available', { cache: 'no-store' }).then(response => response.json()).then(data => setInventory(data.inventory || [])); }, []); const submit = async (event: FormEvent) => { event.preventDefault(); const items = quote.items.map(item => ({ quotationItemId: item.id, inventoryItemIds: selected[item.id] || [] })); const response = await fetch(`/api/crm/quotations/${quote.id}/convert`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ items }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Assign the exact available serials before conversion.'); return; } saved(); }; return <Dialog title={`Convert ${quote.number}`} close={close}><form className="workflow-form" onSubmit={submit}><p className="workflow-help">Assign exactly the quoted quantity from available serialized inventory.</p>{quote.items.map(item => <div className="serial-picker" key={item.id}><strong>{item.sku} · {item.description} · {item.quantity} required</strong>{inventory.filter(device => device.sku === item.sku).slice(0, 20).map(device => <label key={device.id}><input type="checkbox" checked={(selected[item.id] || []).includes(device.id)} onChange={e => setSelected(current => ({ ...current, [item.id]: e.target.checked ? [...(current[item.id] || []), device.id] : (current[item.id] || []).filter(id => id !== device.id) }))}/>{device.serial_number}</label>)}{!inventory.some(device => device.sku === item.sku) && <span className="workflow-help">No available serials match this SKU.</span>}</div>)}{error && <p className="workflow-error">{error}</p>}<Actions close={close} label="Confirm sale"/></form></Dialog>; }
function ReturnDialog({ sale, close, saved }: { sale: Sale; close: () => void; saved: () => void }) { const [reason, setReason] = useState(''); const [selected, setSelected] = useState<Record<string, boolean>>({}); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const items = sale.items.filter(item => selected[item.id]).map(item => ({ saleItemId: item.id, condition: 'Good' })); const response = await fetch(`/api/crm/sales/${sale.id}/returns`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reason, items }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Select at least one sale item.'); return; } saved(); }; return <Dialog title={`Return ${sale.number}`} close={close}><form className="workflow-form" onSubmit={submit}><Field label="Reason"><textarea required rows={3} value={reason} onChange={e => setReason(e.target.value)}/></Field><div className="serial-picker">{sale.items.filter(item => !item.returned).map(item => <label key={item.id}><input type="checkbox" checked={!!selected[item.id]} onChange={e => setSelected({ ...selected, [item.id]: e.target.checked })}/>{item.serialNumber} · {item.description}</label>)}</div>{error && <p className="workflow-error">{error}</p>}<Actions close={close} label="Complete return"/></form></Dialog>; }
function Actions({ close, label = 'Save' }: { close: () => void; label?: string }) { return <div className="workflow-dialog-actions"><button type="button" className="ops-btn ghost" onClick={close}>Cancel</button><button className="ops-btn blue">{label}</button></div>; }
