'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Boxes, PackageCheck, Plus, RefreshCw, ShoppingCart, Users, X } from 'lucide-react';
import { formatOrganizationDate, useOrganizationSettings } from '../organization-settings';
import { useDialogFocus } from '../dialog-focus';

type Supplier = { id: string; code: string; name: string; contact_name?: string; phone?: string; payment_terms?: string; lead_time_days?: number; status: string };
type PurchaseOrder = { id: string; number: string; supplier_name: string; destination?: string; status: string; total?: string | number; expected_at?: string; ordered_quantity: number; received_quantity: number };
type PurchaseOrderItem = { id: string; sku: string; description: string; quantity: number; receivedQuantity: number };
type Receipt = { id: string; number: string; receivedAt: string; notes?: string; receivedBy?: string };
type PurchaseOrderDetail = PurchaseOrder & { supplier_id?: string; items: PurchaseOrderItem[]; receipts?: Receipt[] };

export default function ProcurementWorkflows({ notify, newRecordSignal = 0, query = '' }: { notify: (message: string) => void; newRecordSignal?: number; query?: string }) {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [orders, setOrders] = useState<PurchaseOrder[]>([]);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState('');
  const [dialog, setDialog] = useState<'supplier' | 'supplierEdit' | 'order' | 'orderEdit' | 'receive' | 'orderDetail' | 'supplierDetail' | null>(null);
  const [selectedOrder, setSelectedOrder] = useState<PurchaseOrderDetail | null>(null);
  const [selectedSupplier, setSelectedSupplier] = useState<Supplier | null>(null);
  const load = async () => {
    setBusy(true);
    setError('');
    try {
      const [supplierResponse, orderResponse] = await Promise.all([
        fetch(`/api/suppliers${query ? `?q=${encodeURIComponent(query)}` : ''}`, { cache: 'no-store' }),
        fetch('/api/purchase-orders', { cache: 'no-store' }),
      ]);
      if (!supplierResponse.ok || !orderResponse.ok) throw new Error('Live procurement data is unavailable.');
      const supplierData = await supplierResponse.json();
      const orderData = await orderResponse.json();
      setSuppliers(supplierData.suppliers || []);
      setOrders(orderData.purchaseOrders || []);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : 'Live procurement data is unavailable.');
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => { void load(); }, [query]);
  useEffect(() => { if (newRecordSignal > 0) setDialog('order'); }, [newRecordSignal]);

  const openReceive = async (orderId: string) => {
    setError('');
    const response = await fetch(`/api/purchase-orders/${orderId}`, { cache: 'no-store' });
    if (!response.ok) { setError('Could not load purchase order lines.'); return; }
    const data = await response.json();
    setSelectedOrder(data.purchaseOrder);
    setDialog('receive');
  };

  const openOrder = async (orderId: string) => {
    setError('');
    const response = await fetch(`/api/purchase-orders/${orderId}`, { cache: 'no-store' });
    if (!response.ok) { setError('Could not load purchase order details.'); return; }
    const data = await response.json();
    setSelectedOrder(data.purchaseOrder);
    setDialog('orderEdit');
  };

  const archiveSupplier = async (supplier: Supplier) => { if (!window.confirm(`Archive ${supplier.name}? It will no longer be available for new purchase orders.`)) return; const response = await fetch(`/api/suppliers/${supplier.id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to archive supplier.'); return; } notify(`${supplier.name} archived`); void load(); };
  const archiveOrder = async (order: PurchaseOrder) => { if (!window.confirm(`Cancel ${order.number}?`)) return; const response = await fetch(`/api/purchase-orders/${order.id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to cancel purchase order.'); return; } notify(`${order.number} cancelled`); void load(); };

  const visibleOrders = orders.filter(order => !query || [order.number, order.supplier_name, order.destination, order.status].join(' ').toLowerCase().includes(query.toLowerCase()));
  const outstandingUnits = visibleOrders.reduce((sum, order) => sum + Math.max(0, order.ordered_quantity - order.received_quantity), 0);
  const averageLeadTime = suppliers.length ? Math.round(suppliers.reduce((sum, supplier) => sum + Number(supplier.lead_time_days || 0), 0) / suppliers.length) : 0;

  return <>
    <div className="ops-kpis"><LiveKpi label="Open purchase orders" value={String(visibleOrders.filter(order => !['Closed', 'Received'].includes(order.status)).length)} note={`${visibleOrders.filter(order => order.received_quantity < order.ordered_quantity).length} with outstanding units`} icon={<ShoppingCart size={16}/>} tone="blue"/><LiveKpi label="Units outstanding" value={String(outstandingUnits)} note="Partial receipts preserved" icon={<PackageCheck size={16}/>} tone="amber"/><LiveKpi label="Suppliers" value={String(suppliers.length)} note="Live supplier directory" icon={<Users size={16}/>} tone="purple"/><LiveKpi label="Avg. lead time" value={`${averageLeadTime} days`} note="From supplier records" icon={<Boxes size={16}/>} tone="green"/></div>
    <section className="ops-panel workflow-panel"><div className="ops-panel-head"><div><h2>Connected procurement workflows</h2><p>These actions write to PostgreSQL and preserve receiving and reservation rules.</p></div><button className="link-btn" onClick={() => void load()} disabled={busy}><RefreshCw size={14} className={busy ? 'spin' : ''}/> Refresh</button></div><div className="workflow-actions"><button className="ops-btn ghost" onClick={() => setDialog('supplier')}><Plus size={15}/> Add supplier</button><button className="ops-btn blue" onClick={() => setDialog('order')} disabled={!suppliers.length}><Plus size={15}/> Create purchase order</button></div>{error && <p className="workflow-error" role="alert">{error}</p>}</section>
    <div className="ops-grid-two"><section className="ops-panel"><div className="ops-panel-head"><div><h2>Purchase orders</h2><p>Live approvals, receiving, and delivery commitments.</p></div></div><div className="data-table"><div className="table-head ops-table-head"><span>Order</span><span>Supplier</span><span>Received</span><span>Status</span><span>Action</span></div>{visibleOrders.map(order => <div className="data-row" key={order.id}><button className="row-action" onClick={() => void openOrder(order.id)}>{order.number}</button><span>{order.supplier_name}</span><span>{order.received_quantity}/{order.ordered_quantity}</span><Status value={order.status}/><div className="transfer-card-actions"><button className="row-action" onClick={() => void openOrder(order.id)}>Details</button>{order.received_quantity < order.ordered_quantity && <button className="row-action" onClick={() => void openReceive(order.id)}><PackageCheck size={13}/> Receive</button>}</div></div>)}{!visibleOrders.length && <div className="empty-state"><ShoppingCart size={22}/><strong>No purchase orders</strong><span>Create a live purchase order to begin receiving.</span></div>}</div></section><section className="ops-panel"><div className="ops-panel-head"><div><h2>Supplier directory</h2><p>Live supplier relationships and delivery terms.</p></div></div><div className="data-table"><div className="table-head ops-table-head"><span>Supplier</span><span>Contact</span><span>Lead time</span><span>Status</span><span>Action</span></div>{suppliers.map(supplier => <div className="data-row" key={supplier.id}><strong>{supplier.name}<small>{supplier.code}</small></strong><span>{supplier.contact_name || supplier.phone || '—'}</span><span>{supplier.lead_time_days || 0} days</span><Status value={supplier.status}/><div className="transfer-card-actions"><button className="row-action" onClick={() => { setSelectedSupplier(supplier); setDialog('supplierDetail'); }}>Details</button><button className="row-action" onClick={() => { setSelectedSupplier(supplier); setDialog('supplierEdit'); }}>Edit</button>{supplier.status === 'Active' && <button className="row-action" onClick={() => void archiveSupplier(supplier)}>Archive</button>}</div></div>)}{!suppliers.length && <div className="empty-state"><Users size={22}/><strong>No suppliers</strong><span>Add a supplier to create purchase orders.</span></div>}</div></section></div>
    <section className="ops-panel"><div className="ops-panel-head"><div><h2>Receiving queue</h2><p>Partial deliveries preserve the outstanding balance.</p></div></div><div className="workflow-receiving"><div>{visibleOrders.filter(order => order.received_quantity < order.ordered_quantity).slice(0, 8).map(order => <button key={order.id} className="workflow-order" onClick={() => void openReceive(order.id)}><span>{order.number} · {order.supplier_name}</span><small>{order.received_quantity}/{order.ordered_quantity} received <PackageCheck size={13}/></small></button>)}</div>{!visibleOrders.some(order => order.received_quantity < order.ordered_quantity) && <p className="workflow-help">No outstanding receipts.</p>}</div></section>
    {dialog === 'supplier' && <SupplierDialog close={() => setDialog(null)} onSaved={() => { setDialog(null); notify('Supplier created'); void load(); }}/>} {dialog === 'supplierEdit' && selectedSupplier && <SupplierEditDialog supplier={selectedSupplier} close={() => { setDialog(null); setSelectedSupplier(null); }} onSaved={() => { setDialog(null); setSelectedSupplier(null); notify('Supplier updated'); void load(); }}/>} {dialog === 'order' && <OrderDialog suppliers={suppliers} close={() => setDialog(null)} onSaved={() => { setDialog(null); notify('Purchase order created'); void load(); }}/>} {dialog === 'receive' && selectedOrder && <ReceiveDialog order={selectedOrder} close={() => { setDialog(null); setSelectedOrder(null); }} onSaved={() => { setDialog(null); setSelectedOrder(null); notify('Goods receipt posted and serial inventory created'); void load(); }}/>} {dialog === 'orderDetail' && selectedOrder && <OrderDetailDialog order={selectedOrder} close={() => { setDialog(null); setSelectedOrder(null); }}/>} {dialog === 'supplierDetail' && selectedSupplier && <SupplierDetailDialog supplier={selectedSupplier} close={() => { setDialog(null); setSelectedSupplier(null); }}/>}
    {dialog === 'orderEdit' && selectedOrder && <OrderEditDialog order={selectedOrder} suppliers={suppliers} close={() => { setDialog(null); setSelectedOrder(null); }} onSaved={() => { setDialog(null); setSelectedOrder(null); notify('Purchase order updated'); void load(); }}/>}
  </>;
}

function LiveKpi({ label, value, note, icon, tone }: { label: string; value: string; note: string; icon: React.ReactNode; tone: string }) { return <div className="ops-kpi"><span className={`kpi-icon ${tone}`}>{icon}</span><strong>{value}</strong><span>{label}</span><small>{note}</small></div>; }
function Status({ value }: { value: string }) { return <span className={`status ${value.toLowerCase().replaceAll(' ', '-')}`}>{value}</span>; }
function OrderEditDialog({ order, suppliers, close, onSaved }: { order: PurchaseOrderDetail; suppliers: Supplier[]; close: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ supplierId: order.supplier_id || '', destination: order.destination || '', expectedAt: order.expected_at ? String(order.expected_at).slice(0, 10) : '', status: order.status }); const [items, setItems] = useState(order.items.map(item => ({ sku: item.sku, description: item.description, quantity: String(item.quantity), unitCost: '0' }))); const [error, setError] = useState('');
  const settings = useOrganizationSettings();
  const canEditLines = order.received_quantity === 0;
  const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`/api/purchase-orders/${order.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, expectedAt: form.expectedAt || null, items: canEditLines ? items.map(item => ({ ...item, quantity: Number(item.quantity), unitCost: Number(item.unitCost) })) : undefined }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Unable to update purchase order.'); return; } onSaved(); };
  return <Dialog title={`Edit ${order.number}`} close={close}><form className="workflow-form" onSubmit={submit}><Field label="Supplier"><select disabled={!canEditLines} value={form.supplierId} onChange={e => setForm({ ...form, supplierId: e.target.value })}>{suppliers.map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.code} · {supplier.name}</option>)}</select></Field><Field label="Destination"><input required value={form.destination} onChange={e => setForm({ ...form, destination: e.target.value })}/></Field><div className="workflow-form-grid"><Field label="Expected date"><input type="date" value={form.expectedAt} onChange={e => setForm({ ...form, expectedAt: e.target.value })}/></Field><Field label="Status"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option>Draft</option><option>Pending approval</option><option>Approved</option><option>Cancelled</option></select></Field></div><div className="serial-picker"><strong>Order lines{!canEditLines && ' · locked after receiving'}</strong>{items.map((item, index) => <div className="workflow-form" key={`${item.sku}-${index}`}><div className="workflow-form-grid"><Field label="SKU"><input disabled={!canEditLines} required value={item.sku} onChange={e => setItems(current => current.map((line, lineIndex) => lineIndex === index ? { ...line, sku: e.target.value } : line))}/></Field><Field label="Quantity"><input disabled={!canEditLines} required min="1" type="number" value={item.quantity} onChange={e => setItems(current => current.map((line, lineIndex) => lineIndex === index ? { ...line, quantity: e.target.value } : line))}/></Field></div><Field label="Description"><input disabled={!canEditLines} required value={item.description} onChange={e => setItems(current => current.map((line, lineIndex) => lineIndex === index ? { ...line, description: e.target.value } : line))}/></Field><Field label="Unit cost"><input disabled={!canEditLines} required min="0" step="0.01" type="number" value={item.unitCost} onChange={e => setItems(current => current.map((line, lineIndex) => lineIndex === index ? { ...line, unitCost: e.target.value } : line))}/></Field></div>)}</div>{order.receipts && <div className="serial-picker"><strong>Goods receipt history</strong>{order.receipts.map(receipt => <div className="workflow-help" key={receipt.id}>{receipt.number} · {formatOrganizationDate(receipt.receivedAt, settings)} · {receipt.receivedBy || 'Unknown receiver'}</div>)}</div>}{error && <p className="workflow-error">{error}</p>}<Actions close={close} label="Save purchase order"/></form></Dialog>;
}
function OrderDetailDialog({ order, close }: { order: PurchaseOrderDetail; close: () => void }) { return <Dialog title={`${order.number} details`} close={close}><div className="workflow-form"><div className="workflow-summary"><div><ShoppingCart size={15}/><span><strong>{order.supplier_name}</strong> supplier</span></div><div><PackageCheck size={15}/><span><strong>{order.received_quantity}/{order.ordered_quantity}</strong> received</span></div></div><p className="workflow-help">Destination: {order.destination || '—'}</p><div className="serial-picker"><strong>Order lines</strong>{order.items.map(item => <div key={item.id} className="workflow-help">{item.sku} · {item.description} · {item.receivedQuantity}/{item.quantity} received</div>)}</div><div className="workflow-dialog-actions"><button type="button" className="ops-btn blue" onClick={close}>Close</button></div></div></Dialog>; }
function SupplierDetailDialog({ supplier, close }: { supplier: Supplier; close: () => void }) { return <Dialog title={`${supplier.name} details`} close={close}><div className="workflow-form"><div className="workflow-summary"><div><Users size={15}/><span><strong>{supplier.code}</strong> supplier code</span></div><div><Boxes size={15}/><span><strong>{supplier.lead_time_days || 0} days</strong> lead time</span></div></div><p className="workflow-help">Contact: {supplier.contact_name || '—'} · {supplier.phone || 'No phone recorded'}</p><p className="workflow-help">Payment terms: {supplier.payment_terms || '—'}</p><div className="workflow-dialog-actions"><button type="button" className="ops-btn blue" onClick={close}>Close</button></div></div></Dialog>; }
function SupplierEditDialog({ supplier, close, onSaved }: { supplier: Supplier; close: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ name: supplier.name, contactName: supplier.contact_name || '', phone: supplier.phone || '', paymentTerms: supplier.payment_terms || '', leadTimeDays: String(supplier.lead_time_days || 0), status: supplier.status }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const response = await fetch(`/api/suppliers/${supplier.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, leadTimeDays: Number(form.leadTimeDays) }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setError(data.error || 'Unable to update supplier.'); return; } onSaved(); };
  return <Dialog title={`Edit ${supplier.name}`} close={close}><form className="workflow-form" onSubmit={submit}><Field label="Supplier name"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field label="Contact name"><input value={form.contactName} onChange={e => setForm({ ...form, contactName: e.target.value })}/></Field><Field label="Phone"><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></Field><div className="workflow-form-grid"><Field label="Payment terms"><input value={form.paymentTerms} onChange={e => setForm({ ...form, paymentTerms: e.target.value })}/></Field><Field label="Lead time (days)"><input type="number" min="0" value={form.leadTimeDays} onChange={e => setForm({ ...form, leadTimeDays: e.target.value })}/></Field></div><Field label="Status"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option>Active</option><option>Inactive</option><option>Blocked</option></select></Field>{error && <p className="workflow-error" role="alert">{error}</p>}<div className="workflow-dialog-actions"><button type="button" className="ops-btn ghost" onClick={close}>Cancel</button><button className="ops-btn blue" disabled={saving}>{saving ? 'Saving…' : 'Save supplier'}</button></div></form></Dialog>;
}
function Dialog({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) {
  const dialogRef = useDialogFocus<HTMLDivElement>(close);
  return <div className="workflow-dialog-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><div ref={dialogRef} className="workflow-dialog" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><div className="workflow-dialog-head"><h3>{title}</h3><button onClick={close} aria-label="Close"><X size={16}/></button></div>{children}</div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="workflow-field"><span>{label}</span>{children}</label>; }
function Actions({ close, label }: { close: () => void; label: string }) { return <div className="workflow-dialog-actions"><button type="button" className="ops-btn ghost" onClick={close}>Cancel</button><button className="ops-btn blue">{label}</button></div>; }

function SupplierDialog({ close, onSaved }: { close: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ name: '', contactName: '', phone: '', paymentTerms: '30 days', leadTimeDays: '14' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const response = await fetch('/api/suppliers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, leadTimeDays: Number(form.leadTimeDays) }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setError(data.error || 'Unable to create supplier.'); return; } onSaved(); };
  return <Dialog title="Add supplier" close={close}><form className="workflow-form" onSubmit={submit}><Field label="Supplier name"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field label="Contact name"><input value={form.contactName} onChange={e => setForm({ ...form, contactName: e.target.value })}/></Field><Field label="Phone"><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></Field><div className="workflow-form-grid"><Field label="Payment terms"><input value={form.paymentTerms} onChange={e => setForm({ ...form, paymentTerms: e.target.value })}/></Field><Field label="Lead time (days)"><input type="number" min="0" value={form.leadTimeDays} onChange={e => setForm({ ...form, leadTimeDays: e.target.value })}/></Field></div>{error && <p className="workflow-error" role="alert">{error}</p>}<div className="workflow-dialog-actions"><button type="button" className="ops-btn ghost" onClick={close}>Cancel</button><button className="ops-btn blue" disabled={saving}>{saving ? 'Saving…' : 'Save supplier'}</button></div></form></Dialog>;
}

function OrderDialog({ suppliers, close, onSaved }: { suppliers: Supplier[]; close: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ supplierId: suppliers[0]?.id || '', destination: 'Harare warehouse', sku: '', description: '', quantity: '1', unitCost: '0', expectedAt: '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const response = await fetch('/api/purchase-orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ supplierId: form.supplierId, destination: form.destination, expectedAt: form.expectedAt || undefined, items: [{ sku: form.sku, description: form.description, quantity: Number(form.quantity), unitCost: Number(form.unitCost) }] }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setError(data.error || 'Unable to create purchase order.'); return; } onSaved(); };
  return <Dialog title="Create purchase order" close={close}><form className="workflow-form" onSubmit={submit}><Field label="Supplier"><select required value={form.supplierId} onChange={e => setForm({ ...form, supplierId: e.target.value })}>{suppliers.map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.code} · {supplier.name}</option>)}</select></Field><Field label="Destination"><input required value={form.destination} onChange={e => setForm({ ...form, destination: e.target.value })}/></Field><div className="workflow-form-grid"><Field label="SKU"><input required value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })}/></Field><Field label="Quantity"><input required type="number" min="1" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })}/></Field></div><Field label="Description"><input required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></Field><div className="workflow-form-grid"><Field label="Unit cost"><input required type="number" min="0" step="0.01" value={form.unitCost} onChange={e => setForm({ ...form, unitCost: e.target.value })}/></Field><Field label="Expected date"><input type="date" value={form.expectedAt} onChange={e => setForm({ ...form, expectedAt: e.target.value })}/></Field></div>{error && <p className="workflow-error" role="alert">{error}</p>}<div className="workflow-dialog-actions"><button type="button" className="ops-btn ghost" onClick={close}>Cancel</button><button className="ops-btn blue" disabled={saving}>{saving ? 'Saving…' : 'Create order'}</button></div></form></Dialog>;
}

function ReceiveDialog({ order, close, onSaved }: { order: PurchaseOrderDetail; close: () => void; onSaved: () => void }) {
  const line = order.items.find(item => item.receivedQuantity < item.quantity);
  const remaining = line ? line.quantity - line.receivedQuantity : 0;
  const [quantity, setQuantity] = useState(String(Math.max(1, remaining))); const [serialNumbers, setSerialNumbers] = useState(''); const [location, setLocation] = useState(order.destination || 'Main warehouse'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!line) return; setSaving(true); setError(''); const serials = serialNumbers.split(/[\n,]+/).map(value => value.trim()).filter(Boolean); const response = await fetch(`/api/purchase-orders/${order.id}/receive`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ location, items: [{ purchaseOrderItemId: line.id, quantity: Number(quantity), serialNumbers }] }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setError(data.error || 'Unable to receive stock.'); return; } onSaved(); };
  return <Dialog title={`Receive ${order.number}`} close={close}>{line ? <form className="workflow-form" onSubmit={submit}><p className="workflow-help">{line.sku} · {line.description} · {remaining} units outstanding. Enter one unique serial number per received unit.</p><Field label="Quantity"><input required type="number" min="1" max={remaining} value={quantity} onChange={e => setQuantity(e.target.value)}/></Field><Field label="Serial numbers"><textarea required rows={4} value={serialNumbers} onChange={e => setSerialNumbers(e.target.value)} placeholder="SN-001, SN-002"/></Field><Field label="Location"><input required value={location} onChange={e => setLocation(e.target.value)}/></Field>{error && <p className="workflow-error" role="alert">{error}</p>}<div className="workflow-dialog-actions"><button type="button" className="ops-btn ghost" onClick={close}>Cancel</button><button className="ops-btn blue" disabled={saving}>{saving ? 'Posting…' : 'Post goods receipt'}</button></div></form> : <div className="empty-state"><PackageCheck size={22}/><strong>Nothing outstanding</strong><span>This purchase order is fully received.</span></div>}</Dialog>;
}
