'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, Boxes, Check, CircleDollarSign, Download, FileText, Filter, ShieldCheck } from 'lucide-react';
import { formatCurrency, useOrganizationSettings } from '../organization-settings';

type Summary = { revenue: string; devices_delivered: number; jobs_completed: number; warranty_claims: number };
type Period = { period: string; revenue: string; units: number; jobs: number };
type Drilldown = { title: string; columns: string[]; rows: Record<string, string | number>[] };
type ProductOption = { sku: string; description: string };

export default function ReportsWorkspace({ notify }: { notify: (message: string) => void }) {
  const today = new Date().toISOString().slice(0, 10); const [from, setFrom] = useState(`${new Date().getFullYear()}-01-01`); const [to, setTo] = useState(today); const [region, setRegion] = useState(''); const [product, setProduct] = useState(''); const [regions, setRegions] = useState<string[]>([]); const [products, setProducts] = useState<ProductOption[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [periods, setPeriods] = useState<Period[]>([]); const [error, setError] = useState(''); const [drilldownType, setDrilldownType] = useState(''); const [drilldown, setDrilldown] = useState<Drilldown | null>(null); const [drilldownError, setDrilldownError] = useState('');
  const settings = useOrganizationSettings();
  const params = () => { const query = new URLSearchParams({ from, to }); if (region) query.set('region', region); if (product) query.set('product', product); return query.toString(); };
  const load = async () => { const response = await fetch(`/api/reports/summary?${params()}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Live report data is unavailable.'); return; } setSummary(data.summary); setPeriods(data.periods || []); setError(''); };
  useEffect(() => { void fetch('/api/reports/filters', { cache: 'no-store' }).then(response => response.json()).then(data => { setRegions(data.regions || []); setProducts(data.products || []); }).catch(() => undefined); void load(); }, []);
  const loadDrilldown = async (type: string) => { setDrilldownType(type); setDrilldownError(''); const response = await fetch(`/api/reports/drilldown?type=${type}&${params()}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) { setDrilldown(null); setDrilldownError(data.error || 'Unable to load report detail.'); return; } setDrilldown(data); };
  useEffect(() => { const type = new URLSearchParams(window.location.search).get('drilldown'); if (type) void loadDrilldown(type); }, []);
  const openDrilldown = (type: string) => { setDrilldownType(type); window.history.replaceState(null, '', `/operations?module=Reports&drilldown=${type}`); void loadDrilldown(type); };
  const closeDrilldown = () => { setDrilldownType(''); setDrilldown(null); window.history.replaceState(null, '', '/operations?module=Reports'); };
  const exportReport = (type: string) => { window.open(`/api/exports?type=${type}&${params()}`, '_blank', 'noopener,noreferrer'); notify(`${type.toUpperCase()} export downloaded`); };
  const revenue = Number(summary?.revenue || 0);
  return <>
    <div className="ops-kpis"><LiveKpi label="Revenue in range" value={formatCurrency(revenue, settings.currency)} note={`${from} to ${to}`} icon={<CircleDollarSign size={16}/>} tone="blue"/><LiveKpi label="Devices delivered" value={String(summary?.devices_delivered || 0)} note="Sold or installed inventory" icon={<Boxes size={16}/>} tone="purple"/><LiveKpi label="Jobs completed" value={String(summary?.jobs_completed || 0)} note="Completed service work" icon={<Check size={16}/>} tone="green"/><LiveKpi label="Warranty claims" value={String(summary?.warranty_claims || 0)} note="Claims opened in range" icon={<ShieldCheck size={16}/>} tone="amber"/></div>
    <section className="ops-panel"><div className="ops-panel-head"><div><h2>Management reporting</h2><p>Live server-side totals filterable by date, region, and product</p></div><div className="export-actions"><button onClick={() => exportReport('csv')}><Download size={12}/> CSV</button><button onClick={() => exportReport('xlsx')}><Download size={12}/> XLSX</button><button onClick={() => exportReport('pdf')}><Download size={12}/> PDF</button></div></div><div className="report-filters"><label className="filter-select">From <input type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label className="filter-select">To <input type="date" value={to} onChange={event => setTo(event.target.value)}/></label><label className="filter-select">Region <select value={region} onChange={event => setRegion(event.target.value)}><option value="">All regions</option>{regions.map(item => <option key={item}>{item}</option>)}</select></label><label className="filter-select">Product <select value={product} onChange={event => setProduct(event.target.value)}><option value="">All products</option>{products.map(item => <option key={item.sku} value={item.sku}>{item.sku} · {item.description}</option>)}</select></label><button className="filter-select" onClick={() => void load()}><Filter size={14}/> Apply filters</button></div>{error && <p className="workflow-error">{error}</p>}<div className="report-table"><div className="table-head ops-table-head"><span>Period</span><span>Revenue</span><span>Units</span><span>Jobs</span></div>{periods.map(period => <div className="data-row" key={period.period}><strong>{period.period}</strong><span>{formatCurrency(period.revenue, settings.currency)}</span><span>{period.units}</span><span>{period.jobs}</span></div>)}{!periods.length && <div className="empty-state"><CircleDollarSign size={22}/><strong>No report activity</strong><span>Live sales will appear here after the first confirmed transaction.</span></div>}</div></section>
    <div className="report-cards"><ReportCard title="Stock valuation" detail="By product, batch, supplier, location" icon={<Boxes size={17}/>} open={() => openDrilldown('stock')}/><ReportCard title="Pipeline conversion" detail="Lead source, stage, consultant" icon={<CircleDollarSign size={17}/>} open={() => openDrilldown('pipeline')}/><ReportCard title="Warranty performance" detail="Claims, cost, turnaround, coverage" icon={<ShieldCheck size={17}/>} open={() => openDrilldown('warranty')}/><ReportCard title="Installation turnaround" detail="Jobs, area, installer, sign-off" icon={<Check size={17}/>} open={() => openDrilldown('installation')}/></div>
    {drilldownType && <section className="ops-panel report-drilldown"><div className="ops-panel-head"><div><h2>{drilldown?.title || 'Report detail'}</h2><p>Live filtered detail from {from} to {to}.</p></div><button className="link-btn" onClick={closeDrilldown}><ArrowLeft size={14}/> Back to reports</button></div>{drilldownError && <p className="workflow-error">{drilldownError}</p>}{drilldown && <div className="data-table"><div className="table-head ops-table-head">{drilldown.columns.map(column => <span key={column}>{column}</span>)}</div>{drilldown.rows.map((row, index) => <div className="data-row" key={`${drilldownType}-${index}`}>{drilldown.columns.map(column => <span key={column}>{formatDrilldownValue(row, column, settings.currency)}</span>)}</div>)}{!drilldown.rows.length && <div className="empty-state"><FileText size={22}/><strong>No detail in this range</strong><span>Try a wider reporting range or create a live record.</span></div>}</div>}</section>}
  </>;
}

function LiveKpi({ label, value, note, icon, tone }: { label: string; value: string; note: string; icon: React.ReactNode; tone: string }) { return <div className="ops-kpi"><span className={`kpi-icon ${tone}`}>{icon}</span><strong>{value}</strong><span>{label}</span><small>{note}</small></div>; }
function ReportCard({ title, detail, icon, open }: { title: string; detail: string; icon: React.ReactNode; open: () => void }) { return <button className="report-card" onClick={open}><span className="report-icon">{icon}</span><span><strong>{title}</strong><small>{detail}</small></span></button>; }
function formatDrilldownValue(row: Record<string, string | number>, column: string, currency: string) { const key = column.toLowerCase().replaceAll(' ', '_'); const value = row[key] ?? row[column] ?? '—'; return key.includes('value') ? formatCurrency(value, currency) : String(value); }
