'use client';

import { useEffect, useState } from 'react';
import { Boxes, Check, CircleDollarSign, Download, Filter, ShieldCheck } from 'lucide-react';

type Summary = { revenue: string; devices_delivered: number; jobs_completed: number; warranty_claims: number };
type Period = { period: string; revenue: string; units: number; jobs: number };

export default function ReportsWorkspace({ notify }: { notify: (message: string) => void }) {
  const today = new Date().toISOString().slice(0, 10); const [from, setFrom] = useState(`${new Date().getFullYear()}-01-01`); const [to, setTo] = useState(today); const [summary, setSummary] = useState<Summary | null>(null); const [periods, setPeriods] = useState<Period[]>([]); const [error, setError] = useState('');
  const load = async () => { const response = await fetch(`/api/reports/summary?from=${from}&to=${to}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Live report data is unavailable.'); return; } setSummary(data.summary); setPeriods(data.periods || []); setError(''); };
  useEffect(() => { void load(); }, []);
  const exportReport = (type: string) => { window.open(`/api/exports?type=${type}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`, '_blank', 'noopener,noreferrer'); notify(`${type.toUpperCase()} export downloaded`); };
  const revenue = Number(summary?.revenue || 0);
  return <>
    <div className="ops-kpis"><LiveKpi label="Revenue in range" value={revenue.toLocaleString(undefined, { style: 'currency', currency: 'USD' })} note={`${from} to ${to}`} icon={<CircleDollarSign size={16}/>} tone="blue"/><LiveKpi label="Devices delivered" value={String(summary?.devices_delivered || 0)} note="Sold or installed inventory" icon={<Boxes size={16}/>} tone="purple"/><LiveKpi label="Jobs completed" value={String(summary?.jobs_completed || 0)} note="Completed service work" icon={<Check size={16}/>} tone="green"/><LiveKpi label="Warranty claims" value={String(summary?.warranty_claims || 0)} note="Claims opened in range" icon={<ShieldCheck size={16}/>} tone="amber"/></div>
    <section className="ops-panel"><div className="ops-panel-head"><div><h2>Management reporting</h2><p>Live server-side totals with a selectable reporting range</p></div><div className="export-actions"><button onClick={() => exportReport('csv')}><Download size={12}/> CSV</button><button onClick={() => exportReport('xlsx')}><Download size={12}/> XLSX</button><button onClick={() => exportReport('pdf')}><Download size={12}/> PDF</button></div></div><div className="report-filters"><label className="filter-select">From <input type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label className="filter-select">To <input type="date" value={to} onChange={event => setTo(event.target.value)}/></label><button className="filter-select" onClick={() => void load()}><Filter size={14}/> Apply filters</button></div>{error && <p className="workflow-error">{error}</p>}<div className="report-table"><div className="table-head ops-table-head"><span>Period</span><span>Revenue</span><span>Units</span><span>Jobs</span></div>{periods.map(period => <div className="data-row" key={period.period}><strong>{period.period}</strong><span>{Number(period.revenue).toLocaleString(undefined, { style: 'currency', currency: 'USD' })}</span><span>{period.units}</span><span>{period.jobs}</span></div>)}{!periods.length && <div className="empty-state"><CircleDollarSign size={22}/><strong>No report activity</strong><span>Live sales will appear here after the first confirmed transaction.</span></div>}</div></section>
    <div className="report-cards"><ReportCard title="Stock valuation" detail="By product, batch, supplier, location" icon={<Boxes size={17}/>} notify={notify}/><ReportCard title="Pipeline conversion" detail="Lead source, stage, consultant" icon={<CircleDollarSign size={17}/>} notify={notify}/><ReportCard title="Warranty performance" detail="Claims, cost, turnaround, coverage" icon={<ShieldCheck size={17}/>} notify={notify}/><ReportCard title="Installation turnaround" detail="Jobs, area, installer, sign-off" icon={<Check size={17}/>} notify={notify}/></div>
  </>;
}

function LiveKpi({ label, value, note, icon, tone }: { label: string; value: string; note: string; icon: React.ReactNode; tone: string }) { return <div className="ops-kpi"><span className={`kpi-icon ${tone}`}>{icon}</span><strong>{value}</strong><span>{label}</span><small>{note}</small></div>; }
function ReportCard({ title, detail, icon, notify }: { title: string; detail: string; icon: React.ReactNode; notify: (message: string) => void }) { return <button className="report-card" onClick={() => notify(`${title} drill-down will use the selected date range`)}><span className="report-icon">{icon}</span><span><strong>{title}</strong><small>{detail}</small></span></button>; }
